# Generated by Django 4.2 on 2023-05-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deleted_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
